name: rf_inn_validation
description: Russian Federation INN validation package
version: 0.2.0
homepage: https://github.com/premiumapp-org/rf_inn_validation

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
